apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cicd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-cicd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s-cicd
    spec:
      containers:
      - name: k8s-cicd-container
        image: aravind310730/k8s-cicd-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10